name: Package homebrew

on:
  push:


jobs:
  package-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: recursive

      - name: Register the formulae in homebrew
        run: |
          brew tap axelarnetwork/axelard https://github.com/axelarnetwork/homebrew-axelard.git
          
      - name: install the binary
        continue-on-error: true
        run: |
          brew install axelarnetwork/axelard/axelard@0.10.7
          axelard version
          
