name: Package homebrew

on:
  push:

jobs:
  package-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: recursive

      - name: Create formula
        run: |
          wget --no-check-certificate https://github.com/axelarnetwork/axelar-core/releases/download/v0.32.2/axelard-darwin-amd64-v0.32.2.sha256
          SHA256=$(cat axelard-darwin-amd64-v0.32.2.sha256)        

          echo "class Axelard < Formula
            desc "Axelar Core binary"
            homepage "https://github.com/axelarnetwork/axelar-core"
            url "https://github.com/axelarnetwork/axelar-core/releases/download/v0.32.2/axelard-darwin-amd64-v0.32.2"
            sha256 "$SHA256"
            license "Apache-2.0"

            def install
              bin.install "axelard-darwin-amd64-v0.32.2" => "axelard"
            end

            test do
              system "#{bin}/axelard", "version"
            end
          end" > Formula/axelard.rb
          rm -fr axelard-darwin-amd64-v0.32.2.sha256

      - name: Commit files
        run: |
          git config --local user.email "kalid@axelar.network"
          git config --local user.name "kalid"
          git add --all
          git diff-index --quiet HEAD -- ||  git commit -m "create formula"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Register the formula in homebrew
        run: |
          brew tap axelarnetwork/axelard https://github.com/axelarnetwork/homebrew-axelard.git
          
      - name: install the binary
        continue-on-error: true
        run: |
          brew install axelard
          axelard version